// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import TextareaAutogrow  from "stimulus-textarea-autogrow"
import Notification      from "stimulus-notification"
import CheckboxSelectAll from 'stimulus-checkbox-select-all'

import controllers from "./**/*_controller.js"
import component_controllers from "../../components/**/*_controller.js"

controllers.forEach((controller) => {
  application.register(controller.name, controller.module.default)
})
component_controllers.forEach((controller) => {
  application.register(controller.name, controller.module.default)
})

application.register('textarea-autogrow', TextareaAutogrow)
application.register('notification', Notification)
application.register('checkbox-select-all', CheckboxSelectAll)



